#+TITLE:     outorg.el
#+AUTHOR:    Thorsten Jolitz
#+EMAIL:     tjolitz <at> gmail <dot> com
#+DATE:      2013-02-11 Mo
#+DESCRIPTION:
#+KEYWORDS:
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:nil toc:t \n:nil @:t ::t |:t ^:nil -:t f:t *:t <:nil
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 
#+XSLT:


/outorg is reverse Org-Babel/

* Org-style outline navigation and comment editing in source buffers

** Copyright

Copyright (C) 2013 Thorsten Jolitz
This file is not (yet) part of GNU Emacs

Author: Thorsten Jolitz  (format "tjolitz%sgmail%s" "@" ".com")

** Credits

This library is based on, or rather an extension of, Per Abrahamsen's
'out-xtra.el' (http://tinyurl.com/aql9p97), and may replace it many cases.
Some new ideas were taken from Fabrice Niessen's '.emacs'
(http://www.mygooglest.com/fni/dot-emacs.html#sec-2), and some inspiration
from Eric Schulte's and Dan Davidson's 'Org-babel'
(http://orgmode.org/worg/org-contrib/babel/).

** Commentary

This file provides (almost) the same nice extra features for outline minor
mode like Per Abrahamsen's 'out-xtra':

- Change default minor mode key prefix to `C-c'.
- Complete keybindings and menu support.
- Add command to show top level headers.
- Add command to hide all other entries than the one containing point.

`outorg' follows a different idea than `out-xtra': it consists of generic
functionality that that calculates the adequate outline-regexp and
outline-level for the active major-mode, rather than defining several blocks
of major-mode specific functionality.

New features of `outorg' are:

 1. Generic functionality that should work whereever `comment-region' and
    `uncomment-region' work.
 2. Fontification of headlines (copied from Fabrice Niessen's
    '.emacs')
 3. Toggling between editing in Lisp mode and in Org mode, similar to the
    editing of source-code blocks in Org-mode.

It is highly recommended to use `outorg' together with `outline-magic' for
the Org-style `outline-cycle' command.

** Emacs Version

`outorg.el' works with [GNU Emacs 24.2.1 (x86_64-unknown-linux-gnu, GTK+
Version 3.6.4) of 2013-01-20 on eric]. No attempts of testing with older
versions or other types of Emacs have be made (yet).

** Installation

Insert 

#+begin_src emacs-lisp
(require 'outorg)
#+end_src

in your .emacs file to install.  If you want a different prefix
key, insert first

#+begin_src emacs-lisp
(defvar outline-minor-mode-prefix "\C-c")
#+end_src

or whatever.  The prefix can only be changed before outline (minor)
mode is loaded.

** ChangeLog

| date            | author(s)       | version |
|-----------------+-----------------+---------|
| 2013-02-11      | Thorsten Jolitz |     0.9 |

** Bugs

`outorg' is line-based, it only works with 'one-line' comments, i.e. with
comment-sections like those produced by `comment-region' (a command that
comments or uncomments each line in the region). Those special multi-line
comments found in many programming languages are not recognized and lead to
undefined behaviour. 
